# Dev files
**/*.dockerignore
**/Dockerfile
.venv
**/.gitignore
.python-version
docker-compose-dev.*
generar-compose.sh
Makefile
mi-generador.py
pyproject.toml
README.md
uv.lock
netcat
validar-echo-server.sh

# Ignore server, config and .data
server
client/config.yaml
.data
